language: bash
services: docker

branches:
  only:
    - master

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )

after_script:
  - docker images
  - docker tag $image "$DOCKER_USERNAME/$image"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME/$image"
